# Random Forest regression model config

name: bartpy
target_type: regression
class_name: BARTPyRegressor
probabilistic: true

compatible_target_domains: [real, positive_real, nonnegative_real, integer, nonnegative_integer, positive_integer]

fixed_init_kwargs: {}

tunable_init_kwargs:
  n_trees:
    type: int
    low: 10
    high: 200
  sigma_a:
    type: float
    low: 0.0001
    high: 0.01
  sigma_b:
    type: float
    low: 0.0001
    high: 0.01
  n_samples:
    type: int
    low: 100
    high: 500
  n_burn:
    type: int
    low: 50
    high: 100
  # p_grow and p_prune are hardcoded to 0.5 in bartpy
  alpha:
    type: float
    low: 0.5
    high: 0.99
  beta:
    type: float
    low: 0.5
    high: 4.0
