# Random Forest regression model config

name: bart_reg
target_type: regression
class_name: BARTRegressor
probabilistic: true

compatible_target_domains: [real, positive_real, nonnegative_real, integer, nonnegative_integer, positive_integer]

fixed_init_kwargs:
  random_state: 1234

tunable_init_kwargs:
  m:
    type: int
    low: 50
    high: 500
  draws:
    type: int
    low: 100
    high: 2000
  chains:
    type: int
    low: 1
    high: 4
  sigma_prior_sd:
    type: float
    low: 0.1
    high: 10.0
  bart_alpha:
    type: float
    low: 0.1
    high: 1.0
  bart_beta:
    type: float
    low: 1.0
    high: 10.0
