# LightGBM regression model config

name: bdf_kde
target_type: regression
class_name: BDFModel
probabilistic: true

compatible_target_domains: [real, positive_real, nonnegative_real, integer, nonnegative_integer, positive_integer]

fixed_init_kwargs:
  dist: KDE
  random_state: 1234

tunable_init_kwargs:
  n_trees:
    type: int
    low: 15
    high: 100
  reg_lambda:
    type: float
    low: 0.00001
    high: 1.0
    log: true
  reg_gamma:
    type: float
    low: 0.0001
    high: 1.0
    log: true
  reg_nu:
    type: float
    low: 0.0001
    high: 1.0
    log: true
  min_samples_leaf:
    type: int
    low: 10
    high: 100
  max_depth:
    type: int
    low: 10
    high: 30
  min_samples_split:
    type: int
    low: 50
    high: 200
  subsample:
    type: float
    low: 0.5
    high: 1.0
  colsample:
    type: float
    low: 0.5
    high: 1.0
  eta:
    type: float
    low: 0.001
    high: 0.1
    log: true

tunable_params:
  bandwidth:
    type: categorical
    categories: [scott, silverman]
  kernel:
    type: categorical
    categories: [gaussian, epanechnikov]
  # score_correction:
  #   type: categorical
  #   categories: [loo_cv, bic]

fixed_params:
  score_correction: null  # could use bic too
  # kernel: gaussian
  score_cv_folds: 3
  kde_backend: switch
  bandwidth_policy: parent
  use_compact_support: true  # Whether to use compact support as speedup
