# LightGBM regression model config

name: bdf_normalmunormal
target_type: regression
class_name: BDFRegressor
probabilistic: true

compatible_target_domains: [real, positive_real, nonnegative_real, integer, nonnegative_integer, positive_integer]

fixed_init_kwargs:
  dist: NormalMuNormal
  random_state: 1234
  # max_depth: 50

tunable_init_kwargs:
  n_trees:
    type: int
    low: 5
    high: 200
  reg_lambda:
    type: float
    low: 0.00001
    high: 1.0
    log: true
  reg_gamma:
    type: float
    low: 0.0001
    high: 1.0
    log: true
  reg_nu:
    type: float
    low: 0.0001
    high: 1.0
    log: true
  min_samples_leaf:
    type: int
    low: 5
    high: 50
  # max_depth:
  #   type: int
  #   low: 10
  #   high: 30
  # min_samples_split:
  #   type: int
  #   low: 10
  #   high: 100
  subsample:
    type: float
    low: 0.5
    high: 1.0
  colsample:
    type: float
    low: 0.5
    high: 1.0
  eta:
    type: float
    low: 0.001
    high: 0.1
    log: true

tunable_params:
  sigma_mu_auto_scale:
    type: float
    low: 0.01
    high: 10.0
    log: true
  score_method:
    type: categorical
    categories: [nll, nle]
  # score_correction:
  #   type: categorical
  #   categories: [bic, null]

fixed_params:
  mu_mu: 'auto'  # Set prior mean based on data
  sigma_mu: 'auto'  # Set prior std based on data
  # Should also include loo_cv for normal as 'fast path' is available - missing in Rust
  score_correction: bic  # Bayesian information criterion for score correction if 'nll' is used
