# LightGBM regression model config

name: bdf_normalmeanpseudoalphaskewnormal
target_type: regression
class_name: BDFRegressor
probabilistic: true

compatible_target_domains: [real, positive_real, nonnegative_real, integer, nonnegative_integer, positive_integer]

fixed_init_kwargs:
  dist: NormalMeanPseudoAlphaSkewNormal
  random_state: 1234

tunable_init_kwargs:
  n_trees:
    type: int
    low: 5
    high: 200
  alpha:
    type: float
    low: 0.00001
    high: 1.0
    log: true
  gamma:
    type: float
    low: 0.0001
    high: 1.0
    log: true
  delta:
    type: float
    low: 0.0001
    high: 1.0
    log: true
  min_samples_leaf:
    type: int
    low: 5
    high: 50
  # max_depth:
  #   type: int
  #   low: 10
  #   high: 30
  # min_samples_split:
  #   type: int
  #   low: 10
  #   high: 100
  subsample:
    type: float
    low: 0.5
    high: 1.0
  colsample:
    type: float
    low: 0.5
    high: 1.0
  eta:
    type: float
    low: 0.001
    high: 0.1
    log: true

tunable_params:
  sigma_mu_auto_scale:
    type: float
    low: 0.01
    high: 10.0
    log: true
  m_alpha:
    type: int
    low: 1
    high: 100

fixed_params:
  mu_mu: auto  # Set prior mean based on data
  sigma_mu: auto
  prior_alpha: 0.0  # Prior mean for alpha parameter
  score_regime: nll_bic  # Effective split-score regime
