# LightGBM regression model config

name: lightgbm_reg
target_type: regression
class_name: LGBMRegressor
probabilistic: false

compatible_target_domains: [real, positive_real, nonnegative_real, integer, positive_integer, nonnegative_integer]  # Supports all regression-style targets
# NOTE: Currently, standardization/transformation not applied yet.
log_transform_target: false  # Possibly log-transform outcome, supports true/false, only applied on positive target domains
standardize_target: both  # Possibly standardize outcome (standard scaling), supports 'no', 'only', 'both'

fixed_init_kwargs:
  dist: BetaMVBernoulli
  random_state: 1234

tunable_init_kwargs:
  n_trees:
    type: int
    low: 5
    high: 200
  reg_beta:
    type: float
    low: 0.0
    high: 10.0
    log: true
  reg_lambda:
    type: float
    low: 0.0
    high: 10.0
    log: true
  min_samples_leaf:
    type: int
    low: 5
    high: 50
  min_samples_split:
    type: int
    low: 10
    high: 100
  subsample:
    type: float
    low: 0.5
    high: 1.0
  colsample:
    type: float
    low: 0.5
    high: 1.0
  eta:
    type: float
    low: 0.01
    high: 0.3
    log: true

tunable_params:
  mean_p:
    type: float
    low: 0.0
    high: 1.0

fit_kwargs:
  early_stopping_rounds: 10
  verbose: -1
