# BDF-Full classification: Beta--Bernoulli leaves with tuned effective score regime.

name: bdf_full_clas
target_type: classification
class_name: BDFClassifier
probabilistic: true

compatible_target_domains: [binary]

fixed_init_kwargs:
  dist: BetaMVBernoulli
  random_state: 1234

tunable_init_kwargs:
  n_trees:
    type: int
    low: 5
    high: 200
  alpha:
    type: float
    low: 0.00001
    high: 10.0
  gamma:
    type: float
    low: 0.001
    high: 1.0
    log: true
  delta:
    type: float
    low: 0.001
    high: 1.0
    log: true
  min_samples_leaf:
    type: int
    low: 5
    high: 50
  min_samples_split:
    type: int
    low: 10
    high: 100
  subsample:
    type: float
    low: 0.5
    high: 1.0
  colsample:
    type: float
    low: 0.5
    high: 1.0
  eta:
    type: float
    low: 0.001
    high: 0.1
    log: true

tunable_params:
  var_p:
    type: float
    low: 0.0
    high: .23
  score_regime:
    type: categorical
    categories: [nle, nll_bic, nll]

fixed_params:
  mean_p: auto
