# LightGBM regression model config

name: bdf_gammamvlambdapoisson
target_type: regression
class_name: BDFRegressor
probabilistic: true

compatible_target_domains: [positive_real, nonnegative_real, nonnegative_integer, positive_integer]

fixed_init_kwargs:
  dist: GammaMVLambdaPoisson
  random_state: 1234

tunable_init_kwargs:
  n_trees:
    type: int
    low: 5
    high: 200
  alpha:
    type: float
    low: 0.00001
    high: 1.0
    log: true
  gamma:
    type: float
    low: 0.0001
    high: 1.0
    log: true
  delta:
    type: float
    low: 0.0001
    high: 1.0
    log: true
  min_samples_leaf:
    type: int
    low: 5
    high: 50
  # max_depth:
  #   type: int
  #   low: 10
  #   high: 30
  # min_samples_split:
  #   type: int
  #   low: 10
  #   high: 100
  subsample:
    type: float
    low: 0.5
    high: 1.0
  colsample:
    type: float
    low: 0.5
    high: 1.0
  eta:
    type: float
    low: 0.001
    high: 0.1
    log: true

tunable_params:
  var_lambda_auto_scale:
    type: float
    low: 0.1
    high: 10.0
    log: true
  score_regime:
    type: categorical
    categories: [nle, nll_bic, nll]

fixed_params:
  mean_lambda: auto  # Prior mean = sample mean
  var_lambda: auto   # Prior variance = sample_mean * var_lambda_auto_scale
  raise_on_non_integer: false  # Allow non-integer data (e.g., for count-like continuous targets)
