# LightGBM regression model config

name: bdf_betamvbernoulli
target_type: classification
class_name: BDFModel
probabilistic: true

compatible_target_domains: [binary]

fixed_init_kwargs:
  dist: BetaMVBernoulli
  random_state: 1234

tunable_init_kwargs:
  n_trees:
    type: int
    low: 5
    high: 200
  reg_lambda:
    type: float
    low: 0.00001
    high: 10.0
  reg_gamma:
    type: float
    low: 0.001
    high: 1.0
    log: true
  reg_nu:
    type: float
    low: 0.001
    high: 1.0
    log: true
  min_samples_leaf:
    type: int
    low: 5
    high: 50
  min_samples_split:
    type: int
    low: 10
    high: 100
  # max_depth:
  #   type: int
  #   low: 10
  #   high: 50
  subsample:
    type: float
    low: 0.5
    high: 1.0
  colsample:
    type: float
    low: 0.5
    high: 1.0
  eta:
    type: float
    low: 0.001
    high: 0.1
    log: true

tunable_params:
  var_p:
    type: float
    low: 0.0
    high: .23
  score_method:
    type: categorical
    categories: [nll, nle]

fixed_params:
  score_correction: bic
  mean_p: auto  # Set prior mean based on data
