# LightGBM regression model config

name: bdf_gammamvlambdaexponential
target_type: regression
class_name: BDFModel
probabilistic: true

compatible_target_domains: [positive_real, nonnegative_real, nonnegative_integer, positive_integer]

fixed_init_kwargs:
  dist: GammaMVLambdaExponential
  random_state: 1234

tunable_init_kwargs:
  n_trees:
    type: int
    low: 5
    high: 200
  reg_lambda:
    type: float
    low: 0.0001
    high: 10.0
    log: true
  min_samples_leaf:
    type: int
    low: 5
    high: 50
  min_samples_split:
    type: int
    low: 10
    high: 100
  subsample:
    type: float
    low: 0.5
    high: 1.0
  colsample:
    type: float
    low: 0.5
    high: 1.0
  eta:
    type: float
    low: 0.001
    high: 0.1
    log: true

tunable_params:
  var_lambda:
    type: float
    low: 0.1
    high: 20
    log: true

fixed_params:
  mean_lambda: auto  # Set prior mean based on data
