# LightGBM regression model config

name: conflgbm
target_type: regression
class_name: ConformalizedLGBM
probabilistic: true

compatible_target_domains: [real, positive_real, nonnegative_real, integer, positive_integer, nonnegative_integer]  # Supports all regression-style targets
# NOTE: Currently, standardization/transformation not applied yet.
log_transform_target: false  # Possibly log-transform outcome, supports true/false, only applied on positive target domains
standardize_target: both  # Possibly standardize outcome (standard scaling), supports 'no', 'only', 'both'

fixed_init_kwargs:
  objective: regression
  metric: mse
  boosting_type: gbdt
  verbose: -1
  random_state: 1234
  bagging_seed: 1234
  feature_fraction_seed: 1234
  data_random_seed: 1234
  deterministic: true

tunable_init_kwargs:
  num_leaves:
    type: int
    low: 5
    high: 250
  learning_rate:
    type: float
    low: 0.001
    high: 0.2
    log: true
  max_depth:
    type: int
    low: 2
    high: 15
  n_estimators:
    type: int
    low: 10
    high: 250
  min_child_samples:
    type: int
    low: 5
    high: 100
  subsample:
    type: float
    low: 0.5
    high: 1.0
  colsample_bytree:
    type: float
    low: 0.5
    high: 1.0
