# Main config for regression tests
defaults:
  - _self_
  - model: bdf_normalmeanpseudoalphaskewnormal  # Model config to use

seed: 1234  # Random seed for splitting, cv and tuning
n_trials: 50  # Number of optuna trials per dataset
sample_size: 1000  # Number of samples of predictive distribution to draw for prob. metrics

logging:
  level: DEBUG  # Logging level: DEBUG, INFO, WARNING, ERROR, CRITICAL
