name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.8.1
        with:
          cache: true
          environments: lint
      - name: Run Lint
        run: pixi run -e typecheck lint-ci

  test:
    needs: lint
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - uses: prefix-dev/setup-pixi@v0.8.1
        with:
          cache: true
          run-install: true
          environments: test

      - name: Cache Rust
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: "compiled/rust"

      - name: Build Rust Extension
        run: pixi run build-rust

      - name: Run Tests
        run: pixi run -e test test -- -v

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.8.1
        with:
          cache: true
          environments: docs

      - name: Build Docs
        run: pixi run -e docs docs-build

      - name: Upload Docs Artifact
        uses: actions/upload-artifact@v4
        with:
          name: documentation-html
          path: docs/build/html/
          retention-days: 5
